### ISSUE TITLE
Can only play 1 card in a round

### ISSUE THREAD

**Issue by conn22** [chingk20/Wizard2#2]
After each player (1 human and 3 computers) played a card, I was unable to continue playing cards and the round could not end. This is a major issue and should be resolved ASAP.

**Comment by fukumoto2020** [comment]
We know this is a bug. We are actively working on fixing this

**Comment by jeanhansen** [comment]
More than one card but some issues still

**Comment by chingk20** [comment]
You can now play all the way through the subround.
