### ISSUE TITLE
QUIT & HELP buttons don't do anything

### ISSUE THREAD

**Issue by ghost** [chingk20/Wizard2#3]
At any time during the game, if we pressed either the 'QUIT' or the 'HELP' button, nothing would happen, except that those buttons would register that they were pressed. Therefore, it's not that the buttons themselves don't work, it's that there's no code to execute when those buttons are pressed.

**Comment by fukumoto2020** [comment]
We know this is a bug. We have not started coding the functionality of these buttons yet, but will start after our other bugs are fixed

**Comment by chingk20** [comment]
This is now fixed. Both buttons work now.
