### ISSUE TITLE
Portrait/Landscape Issue

### ISSUE THREAD

**Issue by TheAwesome1123** [chingk20/Wizard2#4]
Report by Samuel Nguyen

Flipping the tablet to the opposite orientation causes the game to restart.

**Comment by jeanhansen** [comment]
Might have something to do with the surface view.  If you flip it twice there is another problem like this that presents itself so we will try to fix both those bugs together.

**Comment by jeanhansen** [comment]
Not as important as our other issues

**Comment by jeanhansen** [comment]
Locked orientation to landscape
